#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=2
#spring.datasource.hikari.pool-name=MyHikariPool
#spring.datasource.hikari.leak-detection-threshold=2000


logging.level.com.zaxxer.hikari=DEBUG
